GRANT USAGE ON SCHEMA agencia TO authenticated;
GRANT USAGE ON SCHEMA agencia_app TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA agencia TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA agencia TO authenticated;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA agencia_app TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA agencia GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated;